---
title: "ARIMA Evaluation"
output:
html_document:
  code_folding: hide
  theme: flatly
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(forecast)
#old data
#covid_1 <- read_xlsx("../Public Records Request 11-17-2020.xlsx")
#new_data
covid_1 <- read_xlsx("../Power BI Source 2-27-2021 Jackson.xlsx")
#New data as a csv
#covid_1 <- read_csv("../Power BI Source 2-27-2021 Jackson.csv")


covid_1$County <- factor(covid_1$County)

covid_rename <- covid_1 %>% 
  rename(
    report_date =`Report Date`,
    released_date = `Released from EIPH Monitoring`,
    age_group = `Age Group (by decade)`,
    exposure = `Source of Exposure`
  )
#This is only for the situation of using the csv instead of the xlsx
  # %>% 
  # select(!c(X11, X12)) %>% 
  # as.Date(report_date, released_date)

neg_values <- covid_rename %>% 
  mutate(neg_val = -1)
data_rename <- covid_rename %>% 
  mutate(pos_val = 1)

reported <- data_rename %>% 
  rename(date = report_date,
         val = pos_val)
released <- neg_values %>% 
  rename(date = released_date,
         val = neg_val)

part_1 <- reported %>% 
  select(date, val) %>% 
  na.omit()
part_2 <- released %>% 
  select(date, val) %>% 
  na.omit()

#part_2_char <- part_2 %>% 
#  as.character(date)




#This is where the error is happening
stacked <- rbind(part_1, part_2) %>% 
  group_by(date) %>% 
  summarise(daily_total = sum(val)) %>% 
  arrange(date) %>% 
  mutate(total_sum = cumsum(daily_total)) %>% 
  select(total_sum)

#%>% 
# This removes the value correctly, but the error still occurs
  #na.omit() %>% 
  #select(total_sum)

cleaned_ts <- stacked[-nrow(stacked),]

clean_df <- as.data.frame(cleaned_ts)
```

```{r}
#This is the not used for the automation of the plotting, thus is not really necessary


covid_ts <- ts(clean_df$total_sum, start = c(2020,73), frequency = 365)
arima_capital <- Arima(covid_ts, order = c(0,3,3))

arima_preds <- predict(arima_capital, 3)

arima_preds$pred[1:3]



c(covid_ts,arima_preds$pred[1:3])

plot(c(covid_ts,arima_preds$pred[1:3]), type = "l")
abline(v = 220)
```

### Use 30 days to predict 5 days

```{r}
#not automated, so not really needed either
train_30 <- clean_df %>% 
  slice(1:30)

true_35 <- clean_df %>% 
  slice(1:35) %>% 
  rename(true_total = total_sum)

ts_30 <- ts(train_30, start = c(2020,73), frequency = 365)
arima_30 <- Arima(ts_30, order = c(0,3,3))

pred_cases <- round(predict(arima_30, 5)$pred[1:5])
pred_df <- as.data.frame(pred_cases)

pred_pos <- pred_df %>% 
  transmute(total_sum = case_when(
    pred_cases < 0 ~ 0,
    TRUE ~ pred_cases
  ))

predicted_total <- train_30 %>% 
  rbind(pred_pos)

both_data <- true_35 %>% 
  cbind(predicted_total)

calculate_1 <- both_data %>% 
  slice(31:35) %>% 
  transmute(squared = (true_total - total_sum)^2) %>% 
  summarise(avg = mean(squared))

ggplot(both_data) +
  geom_line(aes(x = 1:35, y = true_total, group = 2, col = "Actual"), size = 3)+
  geom_line(aes(x = 1:35, y = total_sum, group = 1, col = "Predicted"), size = 1.5)+
  scale_color_manual(name = "Cases",
                     breaks = c("Predicted", "Actual"),
                     values = c("Predicted" = "red2", "Actual" = "black"))


```

## Automate it!

```{r}
#clean_data = data
#30 = train_data
#train_30 = train
#true_35 = true

Covid_arima_fun <- function(data,train_days,predict_days,p,d,q){
train <- data %>% 
  slice(1:train_days)
total_number <- train_days + predict_days
true <- data %>% 
  slice(1:total_number) %>% 
  rename(true_total = total_sum)
ts_obj <- ts(train, start = c(2020,73), frequency = 365)
arima_obj <- Arima(ts_obj, order = c(p,d,q))
pred_cases <- round(predict(arima_obj, predict_days)$pred[1:predict_days])
pred_df <- as.data.frame(pred_cases)
pred_pos <- pred_df %>% 
  transmute(total_sum = case_when(
    pred_cases < 0 ~ 0,
    TRUE ~ pred_cases
  ))
predicted_total <- train %>% 
  rbind(pred_pos)
both_data <- true %>% 
  cbind(predicted_total)
train_plus_1 <- train_days+1
calculate_1 <- both_data %>% 
  slice(train_plus_1:total_number) %>% 
  transmute(squared = (true_total - total_sum)^2) %>% 
  summarise(RMSE = mean(squared))
ggplot(both_data) +
  geom_line(aes(x = 1:total_number, y = true_total, group = 2, col = "Actual"), size = 3)+
  geom_line(aes(x = 1:total_number, y = total_sum, group = 1, col = "Predicted"), size = 1.5)+
  scale_color_manual(name = "Cases",
                     breaks = c("Predicted", "Actual"),
                     values = c("Predicted" = "firebrick", "Actual" = "black"))+
  theme_bw()+
  labs(x = "Number of Days from March 14",
       y = "Case Count",
       title = "Predicted VS. Actual Case Counts Using Arima",
       subtitle = paste("RMSE: ", calculate_1))+
  geom_vline(xintercept = train_days)+
  xlim(train_days-20,total_number + 1)+
  #ylim(500,1000)+
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())
}

Covid_arima_fun(data = clean_df, train_days = 200, predict_days = 5, p = 2, d = 1, q = 2)


```


## Selecting p,d,q

Stationarity refers to the fact that the counts is mean-reverting

Use the Augmented dickey fuller test to determine if the time series is stationary.




## Modeling Procedure using Arima()


```{r}
#Plot the data
ggplot(clean_df, aes(x = 1:221, y = total_sum))+
  geom_line()

#if necessary, transform using boxCox()

#There does not appear to be any evidence for changing variance, so no transformation #is necessary

#If the data are non-stationary, take first differences of them unti lthey become stationary
auto.arima(covid_ts)

my_ts <- ts(clean_df, start = c(2020, 73), frequency = 365)

my_ts %>% diff() %>% ggtsdisplay(main="")


```

